name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
    - name: Set up SpaCy (NLP for Python)
      run: pip3 install spacy
    - name: Run the Python script
      run: |
        which python3
        python3 --version
